---
- name: DÃ©ploiement Flask web app ğŸš€
  user: admin
  hosts: vmawsflaskapp
  tasks:
  - name: ğŸ“ Installation de modules
    apt:
      name:
        - python3-dev
        - python3-pip
        - python3-setuptools
        - docker-compose
    become: yes
  - name: ğŸ Installation du module docker pour python (faculatatif)
    shell: "sudo python3 -m pip install docker && sudo python3 -m pip install docker-compose"
    become: yes
  - name: ğŸ†‘ Supprimer les anciens fichiers
    shell: "rm -rf /home/admin/sample-lb/*"
  - name: â˜ Importer le git
    git:
      repo: https://github.com/vilm725/sample-lb.git
      dest: /home/admin/sample-lb
      version: "master"
      force: yes
      clone: yes
  - name: ğŸ³ ArrÃªt de l'application 
    shell: "docker system prune --all -f && docker kill $(docker ps -q) && docker rm $(docker ps -a -q) && docker rmi $(docker images -q)"
    args:
      chdir: /home/admin/sample-lb
  - name: ğŸ³ Deploiement du conteneur avec l'application
    shell: "sudo docker-compose up --build -d --scale app=3"
    register: dockercreatedebug
    args:
      chdir: /home/admin/sample-lb
  - debug: var=dockercreatedebug.stdout_lines

